# nixpacks.toml

[phases.setup]
nixPkgs = ['bun']
nixpkgsArchive = '8c29968b3a942f2903f90797f9623737c215737c'

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run start'
